### ISSUE TITLE
Crashes with Java 16[BUG]

### ISSUE THREAD

**Issue by PalgamingHD** [Dragon-Seeker/Tropicraft-Fabric-Port#10]
**Describe the bug**
From what I can tell, the game crashes on launch when trying to run with Java 16 on 1.16

**Version Information**
Tropicraft Version:  0.1.2   
Fabric Version:  fabric-api-0.39.2+1.16   

**To Reproduce**
1. Run with fabric 1.16.5 with Java 16 
2. ????
3. Crash

**Crash Log**
```
Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config tropicraft.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:43)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap$$Lambda$78/636782475.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1493)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:494)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:463)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1093)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 8 more
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Process crashed with exit code 1```

**Any and all Mods currently Installed**
```
None
```

**Comment by Dragon-Seeker** [comment]
Can you send me the full log within the logs folder?
